import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero";
import Favicon from "../assets/logo (2).png";

export const metadata: Metadata = {
  title: "Frost Voyage",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: dark)",
        url: "/logo (2).png",
        href: "/logo (2).png",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <main className="relative overflow-hidden">{children}</main>
      <Footer />
    </html>
  );
}
